### ISSUE TITLE
Publishing to PyPI as non-production ready

### ISSUE THREAD

**Issue by RedFantom** [RedFantom/ttkwidgets#14]
Given that with the merge of PR #10 the `ttkwidgets` package now installs correctly onto any user's system, be it Linux or Windows, the package is, in my opinion, ready to be published to PyPI as non-production ready. There are still some issues with some widgets, and they should be worked on, but as long as this is clearly indicated, I'd say that the package is ready, given that it has useful content and a clear target audience. What do you think, @j4321?

**Comment by j4321** [comment]
I am fine with publishing to PyPI. It will make it easier for interested people to test the widgets.

**Comment by RedFantom** [comment]
Published 😄
