### ISSUE TITLE
debug window does not work

### ISSUE THREAD

**Issue by sigoa** [RedFantom/ttkwidgets#19]
from ttkwidgets import debugwindow
try:
    import Tkinter as      tk
    import ttk
except ImportError:
    import tkinter as      tk
    from   tkinter import ttk

root = tk.Tk()
ttk.Button( root, text="Print 111", command="print(111)"  ).pack()
debugwindow.DebugWindow(root)
print (222 , "this works, the button does not, all is broken" )
root.mainloop()

**Comment by RedFantom** [comment]
Thank you for taking the time to open an issue report in our repository. For reference, I have formatted your code in the proper [Markdown](https://guides.github.com/features/mastering-markdown/) manner.
```python
from ttkwidgets import debugwindow
try:
    import Tkinter as tk
    import ttk
except ImportError:
    import tkinter as tk
    from tkinter import ttk

root = tk.Tk()
ttk.Button(root, text="Print 111", command="print(111)").pack()
debugwindow.DebugWindow(root)
print(222, "this works, the button does not, all is broken")
root.mainloop()
```

It appears that you are using the `command` keyword argument for the creation of the `Button` in the wrong way. You see, when you pass the `command` kwarg, the expected value is a `callable` object. A string, as you have passed it, is not a `callable`. Instead, you should use a `lambda`-expression, like so:

```python
ttk.Button(root, text="Print 111", command=lambda: print("111")).pack()
```

Therefore, this does not constitute a bug in the widget, and I will close this issue.
