### ISSUE TITLE
Cannot install package :ValueError: Entry points must be listed in groups

### ISSUE THREAD

**Issue by Zolo-mario** [RedFantom/ttkwidgets#21]
I searched google for solutions but there is no correct answer.

**Comment by RedFantom** [comment]
Thank you for taking the time to open an issue on this repository. However, from the information you have given me, I cannot deduce an actual description of the issue that can help me solve this issue.

Seeing as you have already closed the issue, I assume you have found a solution to your issue. At your earliest convenience, I would like to learn more about the issue and the solution to it, as your issue might also affect other users.

Please provide the following:
- Your Operating System
- Your Python version
- Your Pip and Setuptools versions
- A full stack-trace of the error encountered during installation
