### ISSUE TITLE
Documentation migration to ReadTheDocs

### ISSUE THREAD

**Issue by RedFantom** [RedFantom/ttkwidgets#25]
Discussion on this topic started on [`05b33e1`](https://github.com/RedFantom/ttkwidgets/commit/05b33e15fc8d71b5c7d8b89741d27a01e0625711), but I thought it would be more appropriate to move it to an issue.

This issue is progressing in the `sphinx_doc` branch, created by @j4321.

I will add this repository to my ReadTheDocs account so the documentation is built automatically.

**Comment by RedFantom** [comment]
The documentation on `sphinx_doc` builds just fine on ReadTheDocs, so it is definitely my environment where it is going wrong. It currently looks like [this](https://ttkwidgets.readthedocs.io/en/sphinx_doc/index.html).

**Comment by j4321** [comment]
Maybe we can add the examples in a dedicated section?

**Comment by RedFantom** [comment]
That is a great idea. I'm not sure whether such files can be created by sphinx by itself? Otherwise I could write a small script that formats the examples the proper way.

**Comment by j4321** [comment]
As far as I know sphinx cannot generates these files automatically so writing a script seems the best option.

**Comment by j4321** [comment]
I think the current implementation is good, sphinx was just complaining about one misplaced newline in examples.rst so I corrected the script. 

I also reduced the toctree depth to 1 on the home page because Examples was the only section with displayed subsections.

**Comment by j4321** [comment]
@RedFantom This is not directly related to the documentation, but reading the Installation section made me think about it: If you agree I can make a .deb package for ttkwidgets and make it available in a ppa on my launchpad account.

**Comment by RedFantom** [comment]
Oh, sure! I really wouldn't know how to do that or how to maintain that, but it does sound like it could be useful to some users.

What format would you like for the docstrings? I can try to help out over the next few days, but I'm not sure how much time I will have.

**Comment by j4321** [comment]
Ok great. I think we should use the standard sphinx formatting (https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html). Some of the modules already use it, like in `linklabel.py`.

**Comment by RedFantom** [comment]
I suppose a separate branch would be appropriate.

Thanks for the tips on the TimeLine docstrings! I will get to them as soon as I can.

**Comment by RedFantom** [comment]
@j4321 It's been a while, and I've been busy, but I think the documentation is complete now, right? At least, every widget has a documentation entry and it looks good. Do you agree that it is ready for a PR?

**Comment by j4321** [comment]
@RedFantom I agree, I was thinking about opening a PR but got caught up with other things.
