### ISSUE TITLE
Does tkinter have a checklistbox?

### ISSUE THREAD

**Issue by noval102200** [RedFantom/ttkwidgets#30]
I want to use a checklistbox widget in my project. But tkinter has no checklistbox.
How to implement checklistbox base on tkinter widget like listbox or treeview or other widget.

**Comment by noval102200** [comment]
![Uploading QQ截图20190314233605.png…]()

**Comment by noval102200** [comment]
![QQ截图20190314233605](https://user-images.githubusercontent.com/34784147/54372247-e9f9d500-46b5-11e9-8a65-eae5bc3a3e97.png)

**Comment by RedFantom** [comment]
Checkout the [`CheckboxTreeview`](https://ttkwidgets.readthedocs.io/en/latest/examples/CheckboxTreeview.html) widget included in the `ttkwidgets` package. I believe it does exactly what you want.
![Screenshot from 2019-03-14 21-30-46](https://user-images.githubusercontent.com/15170036/54389494-7ef1d380-46a0-11e9-8609-6a23f5fc8dbd.png)
Checkout the example and the full documentation for details.

**Comment by wekay102200** [comment]
@RedFantom thanks very much for your answer.
I have implemented the checklistbox with CheckboxTreeview.
look below:
![2019-03-20_160042](https://user-images.githubusercontent.com/18589915/54668511-079dc300-4b2a-11e9-915d-90dd864c3d2f.png)
but i found the left space is too large,i think the reason is the tree item +  button is not hidden.
like below:
![2019-03-20_160551](https://user-images.githubusercontent.com/18589915/54668801-bc37e480-4b2a-11e9-88f4-3aaf58f8c489.png)
how to hidden the item +  button ?

**Comment by RedFantom** [comment]
As far as I know, this is not possible with Tkinter or ttk. I have never seen a reference to such an option in any of the documentation sources I have read on the `Treeview`.
The only alternatives that I know of would possibly be [`tkintertreectrl`](http://tkintertreectrl.sourceforge.net/), which I have personally never used before, making the list manually with customized `ttk.Checkbox` widgets with a modified style to make them smaller, or, lastly, you could build your own implementation using a `tk.Canvas` widget, drawing everything procedurally (which would be a lot of work, but would allow you to customize it exactly to your needs). Currently, I do not have time to write an example for such a `Canvas` implementation, unfortunately, but if you would like some examples on how to draw on a `Canvas`, you can check out the `Calendar`, `TimeLine` and color widgets.

**Comment by wekay102200** [comment]
@RedFantom Do you know tkinter text control support multithread?
 when I insert content to text control in multithread method,my program will crashed immediately.
sample code is below:

class FindResultsview(ttk.Frame):
    def __init__(self, master):
        ttk.Frame.__init__(self, master)
        self.text = tk.Text(self)
        self.text.pack(expand=1,fill="both")
        
    def AddLine(self,line_text):
        self.text.insert(tk.END, line_text)
        if not line_text.endswith("\n"):
            self.text.insert(tk.END,"\n")

    def ClearLines(self):
        self.text.delete('1.0','end')


call code sample:

        while line:
            count, foundStart, foundEnd, newText = self.DoFind(findString, None, line, 0, 0, True, matchCase, wholeWord, regExpr)
            if count != -1:
                if needToDisplayFilename:
                    view.AddLine(FILENAME_MARKER + filename + "\n")
                    needToDisplayFilename = False
                line = self.LINE_PREFIX + str(lineNum) + ":" + line
                view.AddLine(line)
                found_line += 1
            line = docFile.readline()

**Comment by j4321** [comment]
@wekay102200 Tkinter does not support multithreading, all actions on the GUI parts need to be done in the main thread.

**Comment by j4321** [comment]
@wekay102200 To answer your question about the size of the left margin, you can change the size of the indicator (invisible in your case) by configuring the style:
```
from ttkwidgets import CheckboxTreeview
from tkinter.ttk import Style

c = CheckboxTreeview()
c.insert('', 'end', text='item 1')
c.insert('', 'end', text='item 2')

s = Style()
s.configure('Checkbox.Treeview.Item', indicatorsize=0)
c.pack()
```
which gives ![screenshot](https://imgur.com/x4R7F4I.png)

**Comment by noval102200** [comment]
@j4321 i have try to use your method below:
from ttkwidgets import CheckboxTreeview
from tkinter.ttk import Style
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

root = tk.Tk()

tree = CheckboxTreeview(root)


tree.insert('', 'end', text='item 1')
tree.insert('', 'end', text='item 2')
s = Style()
s.configure('Checkbox.Treeview.Item', indicatorsize=0)
tree.pack()
root.mainloop()

but the space has not changed yet,what's the reason may be?
![QQ图片20190321233253](https://user-images.githubusercontent.com/34784147/54763906-c395e580-4c31-11e9-868a-c83d434dc27f.png)

**Comment by j4321** [comment]
@noval102200 The reason is that the default windows theme is not fully customizable. You have two options to fix that:
- Use a more customizable theme like clam: `s.theme_use('clam')`
- Change the layout to remove the indicator altogether (I don't have Windows so I cannot check it whether it works):
```
s.layout('Checkbox.Treeview.Item', [('Treeitem.padding',
  {'sticky': 'nswe',
   'children': [('Treeitem.image', {'side': 'left', 'sticky': ''}),
    ('Treeitem.focus',
     {'side': 'left',
      'sticky': '',
      'children': [('Treeitem.text', {'side': 'left', 'sticky': ''})]})]})])
```

**Comment by RedFantom** [comment]
@j4321 Thank you for this solution! This is something I did not know was possible in Tkinter. I checked your solution changing the layout of the default theme in my VM, and the result is quite satisfactory:
![Screenshot_20190321_215853](https://user-images.githubusercontent.com/15170036/54784602-8bd47100-4c24-11e9-914c-9cc3eb2d1edc.png)
The space has definitely disappeared after applying the custom layout. I didn't know it was possible to remove an element like this, awesome!

@wekay102200 About the multi-threading: This is a question that has been answered more times than can be counted on two hands on StackOverflow. If you want to read more on the details, please read [this](https://github.com/RedFantom/mtTkinter/issues/5). For this thread, please keep the questions on-topic and related to the `ttkwidgets` project.

@noval102200 (I think that given the suffix it is safe to assume that you are using multiple accounts?): The solution given by Juliette seems to do exactly what you want, so if this solves your issue then please let us know so the issue can be closed. If you experience more issues related to ttkwidgets, feel free to open up another issue!

**Comment by wekay102200** [comment]
thanks for the answer of master.

**Comment by wekay102200** [comment]
@j4321 i have try your second method,it works fine,tks very much.
