### ISSUE TITLE
Organizing widgets into separate packages

### ISSUE THREAD

**Issue by RedFantom** [RedFantom/ttkwidgets#8]
Given how the amount of widgets has grown, I think it would be appropriate to separate the widgets into separate packages within the `ttkthemes` package.
For example: I think the `fontframe.py` file should be split in files each containing a single class, and then placed into a `font` package. The same would apply to the `colorpicker.py` file (see PR #7 ), as that is currently the largest file of the whole package. 

**Full proposal**
`autocompletely.py` ▶️  `/autocomplete`
`colorpicker.py` ▶️ `/color`
`fontframe.py` ▶️ `/font`
`scrolledframe.py` and `toggledframe.py` ▶️ `/frames`
All the other widgets would remain at the root of the package. What do you think, @j4321?

**Comment by j4321** [comment]
I fully agree. I can take care of colorpicker.

**Comment by RedFantom** [comment]
Merged and done.
